### PR TITLE
fix getGridFs first argument Manager

### PR DESCRIPTION
**Pull request by koma136**

### CODE REVIEW

**Comment by Sammaye** [comment]
Does gridfs work with this fix?

**Comment by koma136** [comment]
read from gridFs - yes
Write - no
not exist method storeFile
Now I'm trying to solve this problem

2017-03-14 10:34 GMT+03:00 Sam Millman <notifications@github.com>:

**Comment by Sammaye** [comment]
Awesome, when you fix that I will merge

**Comment by koma136** [comment]
Hi. may be you merge this pull request
I now use this way
$bucket =Yii::app()->mongodb->selectDatabase()->getGridFs();
$bucket->uploadFromStream('test.txt',$file);

2017-03-14 11:19 GMT+03:00 Sam Millman <notifications@github.com>:

**Comment by Sammaye** [comment]
Did you fix write yet?

**Pull request closed without merging**
